// Generated by https://quicktype.io

import { ApiProperty } from "@nestjs/swagger";
import { Type } from "class-transformer";
import { IsArray, IsNumber, ValidateNested } from "class-validator";
import { ProductResponseDto } from "src/products/dto/product-response.dto";

export class CartResponseProductDto {

    @ApiProperty()
    @IsNumber()
    cartId: number;

    @IsNumber()
    @ApiProperty()
    productId: number;

    @IsNumber()
    @ApiProperty()
    quantity: number;

    @ApiProperty({ type: () => ProductResponseDto})    
    @Type(() => ProductResponseDto)
    product: ProductResponseDto;
}

export class CartResponseDto {

    @ApiProperty()
    id: number;

    @ApiProperty()
    userId: number;

    @ApiProperty()
    createdAt: Date;

    @ApiProperty()
    updatedAt: Date;

    @ApiProperty({
        type: [CartResponseProductDto],
        description: 'Array of cart products'
    })
    @IsArray()
    @ValidateNested({ each: true })
    @Type(() => CartResponseProductDto)
    cartProducts: CartResponseProductDto[];
}